apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  namespace: replace-with-namespace
  name: replace-with-generic-name
  labels:
    labelname: ivo
spec:
  data: replace-with-generic-base64
  description: IVO_description
  secretName: replace-with-generic-secret
  type: generic
